baseURL = "https://less.coffee/"
title = "Arie's Blog"
theme = "etch-less-coffee"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
summaryLength = 10

[params]
  defaultAuthor = "Arie Oldman"
  # shows up in meta tags
  description = "Writing for clarity."
  # shows up in secondary nav line
  greeting = 'Writing for clarity. Hello from Sydney!'
  # shows up in footer
  copyright = 'Made by Arie. Powered by _hugo_ and _gomments_.'
  dark = "auto"
  highlight = true
  # github = "https://github.com/Arizard"
  # linkedin = "https://au.linkedin.com/in/arieoldman"
  # profilePicture = "arie-profile-2.jpeg"

[menu]
  [[menu.main]]
    identifier = "index"
    name = "index"
    title = "index"
    pageRef = "/"
    weight = 10
  # [[menu.main]]
  #   identifier = "posts"
  #   name = "posts"
  #   title = "posts"
  #   pageRef = "/posts"
  #   weight = 10
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    pageRef = "/about"
    weight = 30
  [[menu.footer]]
    identifier = "index"
    name = "index"
    title = "index"
    pageRef = "/"
    weight = 5
  # [[menu.footer]]
  #   identifier = "posts"
  #   name = "posts"
  #   title = "posts"
  #   pageRef = "/posts"
  #   weight = 10
  # [[menu.footer]]
  #   identifier = "artefacts"
  #   name = "artefacts"
  #   title = "artefacts"
  #   pageRef = "/artefacts"
  #   weight = 15
  [[menu.footer]]
    identifier = "about"
    name = "about"
    title = "about"
    pageRef = "/about"
    weight = 30
  [[menu.footer]]
    identifier = "ai-policy"
    name = "ai-policy"
    title = "ai policy"
    pageRef = "/ai"
    weight = 40
  [[menu.footer]]
    identifier = "github"
    name = "github"
    title = "github"
    url = "https://github.com/Arizard"
    weight = 50

[permalinks]
  posts = "/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
      # https://gohugo.io/content-management/markdown-attributes/
        image = true
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    ordered = true

