name = "Rubricism"
license = ""
licenselink = ""
description = "Rubricism theme - fork of Blank theme."
homepage = ""
tags = ["blog", "rubricism", "development"]
features = ["blog"]
min_version = "0.70"

[author]
  name = "Arizard"
  homepage = "https://github.com/Arizard"
